apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      database: water_data
      sslmode: disable
      timescaledb: true
      postgresVersion: 1500
    isDefault: true
    editable: true
